# Generated by Django 3.1.2 on 2020-10-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic_app', '0003_auto_20201022_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='id',
            new_name='userid',
        ),
    ]
