# Generated by Django 3.1.2 on 2020-11-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic_app', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('date_assigned', models.DateField()),
                ('class_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('exam_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('day', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
