# Generated by Django 3.1.2 on 2020-11-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic_app', '0004_assignment_exam_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ass_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
