# Generated by Django 3.1.2 on 2020-10-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic_app', '0004_auto_20201022_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='userid',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
